/* =========================================================================
   frequent.js — vocabulaire coranique le plus fréquent
   Dans l'esprit de « 80% des mots du Coran ». Les mots sont classés par
   thème et, à l'intérieur, à peu près par fréquence décroissante. Chaque
   entrée porte une note brève (sens, étymologie ou repère spirituel) quand
   c'est utile. Les clés sont préfixées « f_ » pour cohabiter avec le
   vocabulaire des leçons dans la répétition espacée.
   Orthographe vérifiée, translittération DIN 31635 simplifiée.
   ========================================================================= */

const Frequent = {
  groupes: [
    {
      titre: 'Outils grammaticaux les plus fréquents',
      intro: 'Ces petits mots reviennent à chaque page du Coran. Les reconnaître au premier coup d\'œil change tout.',
      mots: [
        { ar: 'مِنْ', tr: 'min', fr: 'de, provenant de', cle: 'f_min' },
        { ar: 'فِي', tr: 'fī', fr: 'dans, en', cle: 'f_fi' },
        { ar: 'مَا', tr: 'mā', fr: 'ce que ; ne... pas', cle: 'f_ma' },
        { ar: 'لَا', tr: 'lā', fr: 'non, ne... pas', cle: 'f_la' },
        { ar: 'إِنَّ', tr: 'inna', fr: 'certes, vraiment', cle: 'f_inna' },
        { ar: 'عَلَىٰ', tr: 'ʿalā', fr: 'sur', cle: 'f_ala' },
        { ar: 'إِلَىٰ', tr: 'ilā', fr: 'vers, jusqu\'à', cle: 'f_ila' },
        { ar: 'الَّذِينَ', tr: 'alladhīna', fr: 'ceux qui', cle: 'f_alladhina' },
        { ar: 'مَنْ', tr: 'man', fr: 'qui, celui qui', cle: 'f_man' },
        { ar: 'كُلّ', tr: 'kull', fr: 'tout, chaque', cle: 'f_kull' },
        { ar: 'إِذَا', tr: 'idhā', fr: 'lorsque, quand', cle: 'f_idha' },
        { ar: 'إِنْ', tr: 'in', fr: 'si (condition)', cle: 'f_in' },
        { ar: 'قَدْ', tr: 'qad', fr: 'certes, déjà', cle: 'f_qad' },
        { ar: 'بَعْدَ', tr: 'baʿda', fr: 'après', cle: 'f_bada' },
        { ar: 'بَيْنَ', tr: 'bayna', fr: 'entre', cle: 'f_bayna' },
        { ar: 'وَ', tr: 'wa', fr: 'et', cle: 'f_wa', note: 'La lettre de liaison la plus fréquente : elle se colle au mot suivant.' },
        { ar: 'ثُمَّ', tr: 'thumma', fr: 'puis, ensuite', cle: 'f_thumma', note: 'Marque une succession dans le temps, à la différence de wa (simple addition).' },
        { ar: 'أَوْ', tr: 'aw', fr: 'ou', cle: 'f_aw' },
        { ar: 'بَلْ', tr: 'bal', fr: 'plutôt, bien plus', cle: 'f_bal', note: 'Rectifie ou renchérit sur ce qui précède.' },
        { ar: 'لَٰكِنْ', tr: 'lākin', fr: 'mais', cle: 'f_lakin' },
        { ar: 'عَنْ', tr: 'ʿan', fr: 'de, au sujet de', cle: 'f_an' },
        { ar: 'مَعَ', tr: 'maʿa', fr: 'avec', cle: 'f_maca' },
        { ar: 'حَتَّىٰ', tr: 'ḥattā', fr: 'jusqu\'à, même', cle: 'f_hatta' },
        { ar: 'إِلَّا', tr: 'illā', fr: 'sauf, si ce n\'est', cle: 'f_illa', note: 'Fusion de in + lā. Introduit l\'exception, comme dans lā ilāha illā llāh.' },
        { ar: 'غَيْر', tr: 'ghayr', fr: 'autre que, non', cle: 'f_ghayr' },
        { ar: 'لَمْ', tr: 'lam', fr: 'ne... pas (passé)', cle: 'f_lam', note: 'Nie un verbe à l\'inaccompli mais avec un sens de passé : lam yalid.' },
        { ar: 'لَنْ', tr: 'lan', fr: 'ne... jamais (futur)', cle: 'f_lan' },
        { ar: 'كَيْفَ', tr: 'kayfa', fr: 'comment', cle: 'f_kayfa' },
        { ar: 'هَلْ', tr: 'hal', fr: 'est-ce que', cle: 'f_hal' },
      ],
    },
    {
      titre: 'Allah et les noms divins',
      intro: 'Le mot le plus présent du Coran, et quelques-uns de Ses plus beaux noms.',
      mots: [
        { ar: 'اللَّه', tr: 'allāh', fr: 'Allah', cle: 'f_allah', note: 'Le Nom suprême. Présent près de trois mille fois dans le Coran.' },
        { ar: 'رَبّ', tr: 'rabb', fr: 'Seigneur, Éducateur', cle: 'f_rabb', note: 'Racine ر-ب-ب : celui qui nourrit, élève et mène une chose à sa perfection.' },
        { ar: 'الرَّحْمَـٰن', tr: 'ar-raḥmān', fr: 'le Tout Miséricordieux', cle: 'f_rahman', note: 'Miséricorde immense, embrassant toute la création.' },
        { ar: 'الرَّحِيم', tr: 'ar-raḥīm', fr: 'le Très Miséricordieux', cle: 'f_rahim', note: 'Miséricorde agissante, continue, en particulier envers les croyants.' },
        { ar: 'الْعَلِيم', tr: 'al-ʿalīm', fr: 'l\'Omniscient', cle: 'f_alim', note: 'Racine ع-ل-م du savoir.' },
        { ar: 'الْحَكِيم', tr: 'al-ḥakīm', fr: 'le Sage', cle: 'f_hakim' },
        { ar: 'الْغَفُور', tr: 'al-ghafūr', fr: 'le Pardonneur', cle: 'f_ghafur' },
        { ar: 'الْعَزِيز', tr: 'al-ʿazīz', fr: 'le Tout-Puissant', cle: 'f_aziz' },
        { ar: 'الْمَلِك', tr: 'al-malik', fr: 'le Roi, le Souverain', cle: 'f_malik', note: 'Racine م-ل-ك, la possession et la royauté. Cf. māliki yawmi d-dīn.' },
        { ar: 'الْخَالِق', tr: 'al-khāliq', fr: 'le Créateur', cle: 'f_khaliq', note: 'Racine خ-ل-ق : façonner, mesurer, créer à partir de rien.' },
        { ar: 'الرَّزَّاق', tr: 'ar-razzāq', fr: 'le Pourvoyeur', cle: 'f_razzaq', note: 'Schème intensif faʿʿāl : Celui qui pourvoit sans cesse et pour tous.' },
        { ar: 'السَّمِيع', tr: 'as-samīʿ', fr: 'l\'Audient', cle: 'f_sami', note: 'Souvent couplé à al-baṣīr : Il entend et voit tout.' },
        { ar: 'الْبَصِير', tr: 'al-baṣīr', fr: 'le Clairvoyant', cle: 'f_basir' },
        { ar: 'الْقَدِير', tr: 'al-qadīr', fr: 'le Tout-Puissant, le Capable', cle: 'f_qadir', note: 'Racine ق-د-ر : la mesure et la puissance. Cf. ʿalā kulli shayʾin qadīr.' },
        { ar: 'اللَّطِيف', tr: 'al-laṭīf', fr: 'le Subtil, le Bienveillant', cle: 'f_latif' },
        { ar: 'الْعَظِيم', tr: 'al-ʿaẓīm', fr: 'l\'Immense', cle: 'f_azim' },
      ],
    },
    {
      titre: 'La création d\'Allah',
      intro: 'Les grands mots qui désignent le monde et ses signes.',
      mots: [
        { ar: 'يَوْم', tr: 'yawm', fr: 'jour', cle: 'f_yawm' },
        { ar: 'النَّاس', tr: 'an-nās', fr: 'les gens, les hommes', cle: 'f_nas' },
        { ar: 'أَرْض', tr: 'arḍ', fr: 'terre', cle: 'f_ard' },
        { ar: 'سَمَاء', tr: 'samāʾ', fr: 'ciel', cle: 'f_sama' },
        { ar: 'آيَة', tr: 'āya', fr: 'signe, verset', cle: 'f_aya', note: 'Désigne à la fois un verset et un signe d\'Allah dans la création.' },
        { ar: 'لَيْل', tr: 'layl', fr: 'nuit', cle: 'f_layl' },
        { ar: 'نَار', tr: 'nār', fr: 'feu', cle: 'f_nar' },
        { ar: 'جَنَّة', tr: 'janna', fr: 'jardin, Paradis', cle: 'f_janna', note: 'Racine ج-ن-ن, l\'idée de ce qui est voilé, couvert de verdure.' },
        { ar: 'مَاء', tr: 'māʾ', fr: 'eau', cle: 'f_maa' },
        { ar: 'شَمْس', tr: 'shams', fr: 'soleil', cle: 'f_shams', note: 'Féminin en arabe. Une sourate entière porte son nom (91).' },
        { ar: 'قَمَر', tr: 'qamar', fr: 'lune', cle: 'f_qamar', note: 'Masculin. Donne le nom des « lettres lunaires ».' },
        { ar: 'نَجْم', tr: 'najm', fr: 'étoile', cle: 'f_najm', note: 'Pluriel نُجُوم (nujūm).' },
        { ar: 'جَبَل', tr: 'jabal', fr: 'montagne', cle: 'f_jabal', note: 'Pluriel brisé جِبَال (jibāl).' },
        { ar: 'رِيح', tr: 'rīḥ', fr: 'vent', cle: 'f_rih', note: 'Pluriel رِيَاح (riyāḥ) ; racine ر-و-ح, liée aussi au souffle et à l\'esprit (rūḥ).' },
        { ar: 'نُور', tr: 'nūr', fr: 'lumière', cle: 'f_nur', note: 'Un Nom et une image récurrente : allāhu nūru s-samāwāti wa-l-arḍ.' },
        { ar: 'رِزْق', tr: 'rizq', fr: 'subsistance, don', cle: 'f_rizq', note: 'Tout ce qu\'Allah accorde pour vivre, matériel ou spirituel.' },
      ],
    },
    {
      titre: 'Religion, foi et actes',
      intro: 'Le vocabulaire du cœur et de la pratique.',
      mots: [
        { ar: 'دِين', tr: 'dīn', fr: 'religion, rétribution', cle: 'f_din' },
        { ar: 'إِيمَان', tr: 'īmān', fr: 'foi', cle: 'f_iman', note: 'Racine ء-م-ن, liée à la sécurité et à la confiance du cœur.' },
        { ar: 'حَقّ', tr: 'ḥaqq', fr: 'vérité, droit', cle: 'f_haqq' },
        { ar: 'عَمَل', tr: 'ʿamal', fr: 'œuvre, action', cle: 'f_amal' },
        { ar: 'رَحْمَة', tr: 'raḥma', fr: 'miséricorde', cle: 'f_rahma' },
        { ar: 'عَذَاب', tr: 'ʿadhāb', fr: 'châtiment', cle: 'f_adhab' },
        { ar: 'كِتَاب', tr: 'kitāb', fr: 'livre, Écriture', cle: 'f_kitab' },
        { ar: 'قَلْب', tr: 'qalb', fr: 'cœur', cle: 'f_qalb', note: 'Racine ق-ل-ب, ce qui se retourne, se transforme : siège de la foi.' },
        { ar: 'نَفْس', tr: 'nafs', fr: 'âme, soi', cle: 'f_nafs' },
        { ar: 'خَيْر', tr: 'khayr', fr: 'bien, meilleur', cle: 'f_khayr' },
        { ar: 'صَلَاة', tr: 'ṣalāt', fr: 'prière', cle: 'f_salat', note: 'Le second pilier ; pluriel صَلَوَات (ṣalawāt).' },
        { ar: 'زَكَاة', tr: 'zakāt', fr: 'aumône légale', cle: 'f_zakat', note: 'Racine ز-ك-و : purifier et faire croître. La richesse se purifie en partageant.' },
        { ar: 'صَوْم', tr: 'ṣawm', fr: 'jeûne', cle: 'f_sawm' },
        { ar: 'صَبْر', tr: 'ṣabr', fr: 'patience, endurance', cle: 'f_sabr', note: 'Vertu maîtresse du croyant : wa-tawāṣaw bi-ṣ-ṣabr (al-ʿAṣr).' },
        { ar: 'شُكْر', tr: 'shukr', fr: 'gratitude', cle: 'f_shukr', note: 'Le contraire du kufr (déni) : reconnaître le bienfait et son Auteur.' },
        { ar: 'تَقْوَىٰ', tr: 'taqwā', fr: 'piété, crainte révérencielle', cle: 'f_taqwa', note: 'Racine و-ق-ي : se protéger. Se prémunir par la conscience d\'Allah.' },
        { ar: 'هُدًى', tr: 'hudā', fr: 'guidance, droiture', cle: 'f_huda', note: 'De la racine ه-د-ي. Le Coran se dit hudan li-n-nās, guidance pour les hommes.' },
        { ar: 'أَجْر', tr: 'ajr', fr: 'récompense, salaire', cle: 'f_ajr', note: 'Pluriel أُجُور (ujūr).' },
        { ar: 'سَبِيل', tr: 'sabīl', fr: 'voie, chemin', cle: 'f_sabil', note: 'fī sabīli llāh : « dans la voie d\'Allah ».' },
        { ar: 'ذَنْب', tr: 'dhanb', fr: 'péché, faute', cle: 'f_dhanb', note: 'Pluriel ذُنُوب (dhunūb).' },
      ],
    },
    {
      titre: 'Les personnes',
      intro: 'Ceux que le Coran nomme et appelle.',
      mots: [
        { ar: 'رَسُول', tr: 'rasūl', fr: 'messager, envoyé', cle: 'f_rasul' },
        { ar: 'نَبِيّ', tr: 'nabī', fr: 'prophète', cle: 'f_nabi' },
        { ar: 'قَوْم', tr: 'qawm', fr: 'peuple, communauté', cle: 'f_qawm' },
        { ar: 'مُؤْمِن', tr: 'muʾmin', fr: 'croyant', cle: 'f_mumin' },
        { ar: 'عَبْد', tr: 'ʿabd', fr: 'serviteur, adorateur', cle: 'f_abd' },
        { ar: 'وَلَد', tr: 'walad', fr: 'enfant', cle: 'f_walad' },
        { ar: 'أُمّ', tr: 'umm', fr: 'mère', cle: 'f_umm' },
        { ar: 'أَب', tr: 'ab', fr: 'père', cle: 'f_ab', note: 'Pluriel آبَاء (ābāʾ), les ancêtres.' },
        { ar: 'اِبْن', tr: 'ibn', fr: 'fils', cle: 'f_ibn', note: 'Pluriel بَنُونَ / أَبْنَاء. Au féminin : bint (fille).' },
        { ar: 'مَلَك', tr: 'malak', fr: 'ange', cle: 'f_malak', note: 'Pluriel مَلَائِكَة (malāʾika). À ne pas confondre avec malik, le roi.' },
        { ar: 'شَيْطَان', tr: 'shayṭān', fr: 'diable, démon', cle: 'f_shaytan', note: 'Pluriel شَيَاطِين (shayāṭīn) ; racine liée à l\'éloignement (du bien).' },
        { ar: 'كَافِر', tr: 'kāfir', fr: 'dénégateur, mécréant', cle: 'f_kafir', note: 'Pluriels كَافِرُونَ / كُفَّار. Racine ك-ف-ر : couvrir, donc voiler la vérité.' },
        { ar: 'ظَالِم', tr: 'ẓālim', fr: 'injuste, oppresseur', cle: 'f_zalim', note: 'Pluriel ظَالِمُونَ / ظَلَمَة. Le ẓulm, c\'est mettre une chose hors de sa place.' },
        { ar: 'صَالِح', tr: 'ṣāliḥ', fr: 'vertueux, intègre', cle: 'f_salih', note: 'D\'où aṣ-ṣāliḥāt, les bonnes œuvres.' },
      ],
    },
    {
      titre: 'Verbes très fréquents',
      intro: 'Le moteur des récits coraniques.',
      mots: [
        { ar: 'قَالَ', tr: 'qāla', fr: 'il a dit', cle: 'f_qala', note: 'Le verbe le plus fréquent du Coran : les paroles y abondent.' },
        { ar: 'كَانَ', tr: 'kāna', fr: 'il était, il fut', cle: 'f_kana' },
        { ar: 'آمَنَ', tr: 'āmana', fr: 'il a cru', cle: 'f_amana' },
        { ar: 'خَلَقَ', tr: 'khalaqa', fr: 'il a créé', cle: 'f_khalaqa' },
        { ar: 'جَعَلَ', tr: 'jaʿala', fr: 'il a fait, il a placé', cle: 'f_jaala' },
        { ar: 'عَلِمَ', tr: 'ʿalima', fr: 'il a su', cle: 'f_alima' },
        { ar: 'عَبَدَ', tr: 'ʿabada', fr: 'il a adoré', cle: 'f_abada' },
        { ar: 'كَفَرَ', tr: 'kafara', fr: 'il a mécru, il a renié', cle: 'f_kafara', note: 'Racine ك-ف-ر, l\'idée de couvrir, donc de voiler la vérité.' },
        { ar: 'أَنْزَلَ', tr: 'anzala', fr: 'il a fait descendre, révélé', cle: 'f_anzala' },
        { ar: 'هَدَىٰ', tr: 'hadā', fr: 'il a guidé', cle: 'f_hada' },
        { ar: 'جَاءَ', tr: 'jāʾa', fr: 'il est venu', cle: 'f_jaa', note: 'Verbe « creux » : sa racine ج-ي-ء contient un yāʾ qui s\'efface.' },
        { ar: 'دَخَلَ', tr: 'dakhala', fr: 'il est entré', cle: 'f_dakhala', note: 'Opposé de kharaja (sortir).' },
        { ar: 'خَرَجَ', tr: 'kharaja', fr: 'il est sorti', cle: 'f_kharaja' },
        { ar: 'رَأَىٰ', tr: 'raʾā', fr: 'il a vu', cle: 'f_raa', note: 'Racine ر-ء-ي ; donne aussi la « vision » (ruʾyā).' },
        { ar: 'وَجَدَ', tr: 'wajada', fr: 'il a trouvé', cle: 'f_wajada' },
        { ar: 'أَخَذَ', tr: 'akhadha', fr: 'il a pris, il a saisi', cle: 'f_akhadha' },
        { ar: 'أَرَادَ', tr: 'arāda', fr: 'il a voulu', cle: 'f_arada', note: 'D\'où l\'irāda, la volonté.' },
        { ar: 'ضَرَبَ', tr: 'ḍaraba', fr: 'il a frappé ; il a proposé (un exemple)', cle: 'f_daraba', note: 'ḍaraba mathalan : « il a donné un exemple », tournure coranique fréquente.' },
        { ar: 'نَظَرَ', tr: 'naẓara', fr: 'il a regardé, considéré', cle: 'f_nazara' },
      ],
    },
    {
      titre: 'Mots du quotidien (présents dans le Coran)',
      intro: 'Des mots concrets, faciles à imaginer, qui parlent aussi de la création : ils donnent vite de quoi nommer le monde autour de soi.',
      mots: [
        { ar: 'رَجُل', tr: 'rajul', fr: 'homme', cle: 'q_rajul' },
        { ar: 'اِمْرَأَة', tr: 'imraʾa', fr: 'femme', cle: 'q_imraa' },
        { ar: 'بِنْت', tr: 'bint', fr: 'fille', cle: 'q_bint' },
        { ar: 'بَيْت', tr: 'bayt', fr: 'maison', cle: 'q_bayt' },
        { ar: 'شَجَرَة', tr: 'shajara', fr: 'arbre', cle: 'q_shajara' },
        { ar: 'نَخْلَة', tr: 'nakhla', fr: 'palmier', cle: 'q_nakhla' },
        { ar: 'جَبَل', tr: 'jabal', fr: 'montagne', cle: 'q_jabal' },
        { ar: 'بَحْر', tr: 'baḥr', fr: 'mer', cle: 'q_bahr' },
        { ar: 'نَهَر', tr: 'nahar', fr: 'rivière, fleuve', cle: 'q_nahar' },
        { ar: 'طَيْر', tr: 'ṭayr', fr: 'oiseau', cle: 'q_tayr' },
        { ar: 'خُبْز', tr: 'khubz', fr: 'pain', cle: 'q_khubz' },
        { ar: 'لَبَن', tr: 'laban', fr: 'lait', cle: 'q_laban' },
        { ar: 'جَمَل', tr: 'jamal', fr: 'chameau', cle: 'q_jamal' },
        { ar: 'نَاقَة', tr: 'nāqa', fr: 'chamelle', cle: 'q_naqa' },
        { ar: 'بَاب', tr: 'bāb', fr: 'porte', cle: 'q_bab', note: 'Pluriel أَبْوَاب (abwāb).' },
        { ar: 'مَدِينَة', tr: 'madīna', fr: 'ville', cle: 'q_madina', note: 'Pluriel مُدُن (mudun) ; même racine que dīn et yawm ad-dīn.' },
        { ar: 'يَد', tr: 'yad', fr: 'main', cle: 'q_yad', note: 'Pluriel أَيْدٍ (aydin).' },
        { ar: 'وَجْه', tr: 'wajh', fr: 'visage, face', cle: 'q_wajh', note: 'Pluriel وُجُوه (wujūh). wajhu llāh : « la Face d\'Allah ».' },
        { ar: 'عَيْن', tr: 'ʿayn', fr: 'œil, source', cle: 'q_ayn', note: 'Un même mot pour l\'œil et la source d\'eau ; pluriel عُيُون (ʿuyūn).' },
      ],
    },
    {
      titre: 'Salutations et politesse',
      intro: 'L\'arabe vivant que l\'on échange chaque jour. Ces formules vous permettent déjà de saluer et de vous présenter.',
      mots: [
        { ar: 'السَّلَامُ عَلَيْكُمْ', tr: 'as-salāmu ʿalaykum', fr: 'que la paix soit sur vous', cle: 'x_salam' },
        { ar: 'وَعَلَيْكُمُ السَّلَام', tr: 'wa-ʿalaykumu s-salām', fr: 'et sur vous la paix (réponse)', cle: 'x_wasalam' },
        { ar: 'كَيْفَ حَالُكَ', tr: 'kayfa ḥāluka', fr: 'comment vas-tu ?', cle: 'x_kayfa' },
        { ar: 'بِخَيْر', tr: 'bi-khayr', fr: 'bien, en bonne santé', cle: 'x_bikhayr' },
        { ar: 'شُكْرًا', tr: 'shukran', fr: 'merci', cle: 'x_shukran' },
        { ar: 'عَفْوًا', tr: 'ʿafwan', fr: 'de rien, je vous en prie', cle: 'x_afwan' },
        { ar: 'بَارَكَ اللَّهُ فِيكَ', tr: 'bāraka llāhu fīka', fr: 'qu\'Allah te bénisse', cle: 'x_baraka' },
        { ar: 'مَا اسْمُكَ', tr: 'mā smuka', fr: 'quel est ton nom ?', cle: 'x_ism' },
        { ar: 'مِنْ أَيْنَ أَنْتَ', tr: 'min ayna anta', fr: 'd\'où es-tu ?', cle: 'x_minayna' },
        { ar: 'مَعَ السَّلَامَة', tr: 'maʿa s-salāma', fr: 'au revoir', cle: 'x_maasalama' },
      ],
    },
  ],

  // Liste à plat (pratique pour la révision et les statistiques)
  tous() {
    const out = [];
    this.groupes.forEach((g) => g.mots.forEach((m) => out.push(m)));
    return out;
  },
};
